In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/myanmards/resource_files/master/regression-one.csv')
df.head()

Country  Year      Status  Life expectancy  Adult Mortality  \
0  Afghanistan  2015  Developing             65.0            263.0   
1  Afghanistan  2014  Developing             59.9            271.0   
2  Afghanistan  2013  Developing             59.9            268.0   
3  Afghanistan  2012  Developing             59.5            272.0   
4  Afghanistan  2011  Developing             59.2            275.0   

   infant deaths  Alcohol  percentage expenditure  Hepatitis B  Measles  ...  \
0             62     0.01               71.279624         65.0     1154  ...   
1             64     0.01               73.523582         62.0      492  ...   
2             66     0.01               73.219243         64.0      430  ...   
3             69     0.01               78.184215         67.0     2787  ...   
4             71     0.01                7.097109         68.0     3013  ...   

   Polio  Total expenditure  Diphtheria  HIV/AIDS         GDP  Population  \
0    6.0               8.16        65.0       0.1  584.259210  33736494.0   
1   58.0               8.18        62.0       0.1  612.696514    327582.0   
2   62.0               8.13        64.0       0.1  631.744976  31731688.0   
3   67.0               8.52        67.0       0.1  669.959000   3696958.0   
4   68.0               7.87        68.0       0.1   63.537231   2978599.0   

   thinness 1-19 years  thinness 5-9 years  Income composition of resources  \
0                 17.2                17.3                            0.479   
1                 17.5                17.5                            0.476   
2                 17.7                17.7                            0.470   
3                 17.9                18.0                            0.463   
4                 18.2                18.2                            0.454   

   Schooling  
0       10.1  
1       10.0  
2        9.9  
3        9.8  
4        9.5  

[5 rows x 22 columns]

In [7]:
df.rename(columns={'Life expectancy': 'life-expect'}, inplace=True)
df = df.dropna()
df.shape

(1649, 22)

In [9]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Country, Year, Status, life-expect, Adult Mortality, infant deaths, Alcohol, percentage expenditure, Hepatitis B, Measles, BMI, under-five deaths, Polio, Total expenditure, Diphtheria, HIV/AIDS, GDP, Population, thinness 1-19 years, thinness 5-9 years, Income composition of resources, Schooling]
Index: []

[0 rows x 22 columns]

In [11]:
!pip install sklearn

Using legacy 'setup.py install' for sklearn, since package 'wheel' is not installed.
    Running setup.py install for sklearn: started
    Running setup.py install for sklearn: finished with status 'done'


In [12]:
from sklearn.linear_model import LinearRegression

slr = LinearRegression()
SLRX = df[['Schooling']]
Y = df['life-expect']
slr.fit(SLRX, Y)

LinearRegression()

In [13]:
SLRYhat = slr.predict(SLRX)

In [14]:
print(SLRYhat[0:4])

[64.6771856  64.44820695 64.2192283  63.99024965]


In [16]:
from sklearn.metrics import mean_squared_error

SLR_MSE = mean_squared_error(df['life-expect'], SLRYhat)
print('MSE for Simple Linear Regression : ', SLR_MSE)

MSE for Simple Linear Regression :  36.39144686879598


In [17]:
SLR_R2 = slr.score(SLRX, Y)
print('R2 for Simple Linear Regression : ', SLR_R2)

R2 for Simple Linear Regression :  0.5294454639356108


In [18]:
MLRX = df[['GDP', 'Alcohol', 'BMI', 'Schooling']]
mlr = LinearRegression()
mlr.fit(MLRX, Y)

LinearRegression()

In [19]:
MLRYhat = mlr.predict(MLRX)
print(MLRYhat[0:4])

[64.24861418 64.01295717 63.77621795 63.54168785]


In [20]:
MLR_MSE = mean_squared_error(df['life-expect'], MLRYhat)
print('MSE for Multiple Linear Regression : ', MLR_MSE)

MSE for Multiple Linear Regression :  32.66263978796142


In [22]:
MLR_R2 = mlr.score(MLRX, Y)
print('R2 for Multiple Linear Regression : ', MLR_R2)

R2 for Multiple Linear Regression :  0.5776602846411929


In [23]:
PRX = df['Schooling']
f = np.polyfit(PRX, Y, 3)
PR = np.poly1d(f)

In [24]:
PRYhat = PR(PRX)
print(PRYhat[0:4])

[63.54170723 63.28970051 63.04117145 62.79627248]


In [25]:
PR_MSE = mean_squared_error(df['life-expect'], PRYhat)
print('MSE for Polynomial Regression : ', PR_MSE)

MSE for Polynomial Regression :  34.73390295312004


In [26]:
from sklearn.metrics import r2_score
PR_R2 = r2_score(df['life-expect'], PRYhat)
print('R2 for Polynomial Regression : ', PR_R2)

R2 for Polynomial Regression :  0.5508781047168166


In [27]:
print('Simple Linear Regression')
print('MSE for Simple Linear Regression : ', SLR_MSE)
print('R2 for Simple Linear Regression : ', SLR_R2)

Simple Linear Regression
MSE for Simple Linear Regression :  36.39144686879598
R2 for Simple Linear Regression :  0.5294454639356108


In [28]:
print('Multiple Linear Regression')
print('MSE for Multiple Linear Regression : ', MLR_MSE)
print('R2 for Multiple Linear Regression : ', MLR_R2)

Multiple Linear Regression
MSE for Multiple Linear Regression :  32.66263978796142
R2 for Multiple Linear Regression :  0.5776602846411929


In [29]:
print('Polynomial Regression')
print('MSE for Polynomial Regression : ', PR_MSE)
print('R2 for Polynomial Regression : ', PR_R2)

Polynomial Regression
MSE for Polynomial Regression :  34.73390295312004
R2 for Polynomial Regression :  0.5508781047168166
